[project]
name = "centripump-phm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "cfshine", email = "17773303593@139.com" }
]
requires-python = ">=3.11"
dependencies = [
    "grandalf>=0.8",
    "langchain>=1.4.0",
]

[project.scripts]
centripump-phm = "centripump_phm:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
